// Generated by icon-spritesheet

export const iconNames = [
  'AppWindow',
  'Bold',
  'FileCode2',
  'Italic',
  'Popcorn',
  'Underline',
] as const

export type IconName = typeof iconNames[number]
