import type { IconSpriteConfig } from '../images/@types/icon-spritesheet.types';

// Used with manual run using ws:sprites to create static assets
export const staticSpriteConfig: IconSpriteConfig[] = [
  {
    inputDir: '../../node_modules/lucide-static/icons',
    outputDir: 'src/vibrant/assets',
    spriteFileName: 'lucide-sprites.svg',
    typesFileName: 'src/vibrant/@types/lucide-sprites.ts',
    inputFilespec: [
      'arrow-down.svg',
      'arrow-left.svg',
      'arrow-right.svg',
      'arrow-up.svg',
      'badge-check.svg',
      'calendar.svg',
      'check.svg',
      'chevrons-down-up.svg',
      'chevrons-up-down.svg',
      'chevron-down.svg',
      'chevron-left.svg',
      'chevron-right.svg',
      'chevron-up.svg',
      'circle-alert.svg',
      'circle-check.svg',
      'circle-question-mark.svg',
      'circle-small.svg',
      'circle.svg',
      'dot.svg',
      'ellipsis-vertical.svg',
      'ellipsis.svg',
      'house.svg',
      'info.svg',
      'loader-circle.svg',
      'loader.svg',
      'moon.svg',
      'panel-bottom.svg',
      'panel-left.svg',
      'panel-right.svg',
      'panel-top.svg',
      'search.svg',
      'slash.svg',
      'sun.svg',
      'trash-2.svg',
      'user-round.svg',
      'x.svg',
    ],
  },
  {
    inputDir: '../../node_modules/lucide-static/icons',
    outputDir: 'src/vibrant/assets',
    spriteFileName: 'example-sprites.svg',
    typesFileName: 'src/vibrant/@types/example-sprites.ts',
    inputFilespec: ['app-window.svg', 'bold.svg', 'file-code-2.svg', 'italic.svg', 'popcorn.svg', 'underline.svg'],
  },
];
